import express from "express";
import cors from "cors";
import guidelines from "./routes/guidelines.js";
import data from "./routes/data.js";
import chat from "./routes/chat.js";
const app = express();
app.use(cors());
app.use(express.json());
app.get("/", (_req, res) => res.json({ ok: true, name: "JD Talk API" }));
app.use("/api/guidelines", guidelines);
app.use("/api/data", data);
app.use("/api/chat", chat);
const PORT = process.env.PORT || 8080;
app.listen(PORT, () => console.log("JD Talk API on", PORT));